name: Premier League ETL Pipeline

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Configure Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        working-directory: ./data_pipeline
        run: poetry install --no-interaction

      - name: Execute ETL Script
        working-directory: ./data_pipeline
        env:
          # ENV variables
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # Proxy
          HTTP_PROXY: ${{ secrets.WEBSHARE_PROXY }}
          HTTPS_PROXY: ${{ secrets.WEBSHARE_PROXY }}

          NO_PROXY: localhost,127.0.0.1,::1
        run: poetry run python main.py